### ISSUE TITLE
email verification fails on browseridux.org

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1180]
Email verification failed with two different email providers. 
Video at http://accounts.usertesting.com/ViewVideo.aspx?file=giiVho%2fTYZ0%3d
# 

Instructions given to testers:

Scenario:
---You will need to use an email address you can receive mail at.---

---This is NOT the real Netflix site, it's only a simulation.---

Scenario: You are an active Netflix customer.

Tasks:
Task 1: Log-in to Netflix.

Task 2: Enter a password.

Task 3: Confirm your email address.

**Comment by lloyd** [comment]
AWS cutting email off was the cause, redeployed on a different acct, AWS contacted.  should be fixed for now!

**Comment by skinny97214** [comment]
I ran a test yesterday and it also failed. Tried again this am and its still failing for me. :(

**Comment by lloyd** [comment]
Got mail from AWS at February 24, 2012 12:01:54 PM MST that email delivery is fixed.  testing...

browseridux.org appears to be down.  hmm.  no matter.

tried via netflix_test_a.myfavoritebeer.org - email delivery works fast via gmail and mozilla
tried via netflix_test_b.myfavoritebeer.org - email delivery works fast via gmail and mozilla
tried via feature886.myfavoritebeer.org - email delivery works fast via gmail and mozilla.

closing down, assuming that the problem is now resolved via AWS.  please retest and reopen if needed.
