### ISSUE TITLE
email address handling in new primary user signup is case sensitive

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2551]
STR

Either run `node ./tests/new-user/new-user-primary-test.js` or the following:
1) Go to 123done.org and click on sign in
2) enter <someemail>@eyedee.me where 'someemail' is a string with an upper case character
3) dialog fails to dismiss and login is not completed. Error console says:
    Error: uncaught exception: invalid email (FF,Chrome)

**Comment by shane-tomlinson** [comment]
Link to #2891

**Comment by jrgm** [comment]
re-gift upon @6a68 - another case issue.

**Comment by jaredhirsch** [comment]
fixed by #3078

**Comment by jrgm** [comment]
Reopening. And bleh.

So, for the manual STR, this still fails in current dev.

The automated test passes because (see above) "use lowercase alphanum for restmail email until GH-2551 is fixed
https://github.com/mozilla/browserid/blob/dev/automation-tests/lib/restmail.js#L16.

**Comment by jaredhirsch** [comment]
sadly I can repro this. digging in.

**Comment by jrgm** [comment]
Just remove this line
    https://github.com/mozilla/browserid/blob/dev/automation-tests/lib/restmail.js#L16
and run 
    ./scripts/run-all.js -e train0301 -p 14 --platform win7_firefox_16 -t new-user-primary-test
and that would fail (unless it's really lucky and doesn't pick any uppercase characters).

**Comment by jaredhirsch** [comment]
Not totally sure but this might be a bug in eyedee.me. It downcases user names:

https://github.com/mozilla/eyedee.me/blob/master/lib/wsapi.js#L33

but we are agnostic about hanging onto the email _as typed by the user_, so my suspicion is that we're getting an assertion for the downcased name (somedude@eyedee.me), while we are expecting the version entered by the user (Somedude@eyedee.me).

Not quite sure but out of time for the day. State.js line 340 is where you can set a debugger to catch the failure + inspect the stack.

**Comment by callahad** [comment]
Check out #2680 -- sounds like the same thing.

**Comment by jaredhirsch** [comment]
@callahad is right--the underlying question is, if a user supplies "alice@idp" and the primary says, actually that user is "bob@idp", which one do we trust? Seems like we at least need to give the user an "are you sure you want to sign in as bob@idp" confirmation screen.

In this case, eyedee.me is telling us the user is "somedude@eyedee.me" after a user tries to login as "Somedude@eyedee.me". Unfortunately, we need to take a biggish stand to solve this particular case.

So, this is going to stay open until normalization _Phase 2_, when we actually decide how to handle these kinds of issues.

Bumping down to 4-stars for now. To be continued.

**Comment by shane-tomlinson** [comment]
@6a68, @callahad and I discussed this at FOSDEM and how it could potentially be used by an IdP to dynamically provision new email addresses.

The use case is:
I visit a new RP that I just don't trust. They ask for an email address but I don't want to give them one of my own addresses. I want a dynamically provisioned address that shields my identity.

The flow is:
1) I visit a new RP that requires me to sign in, but I don't want to give them one of my main email addresses.
2) I type in NEW_EMAIL@makemeanaddress.com
3) I am redirected to makemeanaddress.com, they provision a new, random address: aba362sd@makemeanaddress.com
4) I am redirected back to Persona. Persona notices the discrepancy and asks me if the change of address is alright. I click "yeah"
5) I sign in to the new RP with this dynamically provisioned address.

**Comment by callahad** [comment]
I'd advocate for making this an error right now, rather than silently breaking, and revisiting it as a prompt-the-user sorta thing for Q2.

**Comment by jrgm** [comment]
Hey, where does this stand. With eyedee.me, I still have the error in the dialog (due to eyedee.me as an IdP changing the email address). But really, this bug is proxy for the problem noted in https://github.com/mozilla/browserid/issues/2551#issuecomment-14637202

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
