### ISSUE TITLE
watch() API problems also affect Safari 7 on Mac OS 10.9

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3925]
Downloaded the next Mac OS version and found that, against prod, 123done is exhibiting the same badness as we saw with the 5-star iOS bug #3905. @pdehaan filed a similar bug for Safari 6.1, #3916.

I'm filing this bug so that we have it, and to provoke conversation around eliminating third-party cookie requirements sooner than later.

STR:
1. Install 10.9 (I did this in a vm by creating a 10.8 VM, copying over the 10.9 install app, then running it on the guest).
2. open up safari, go to 123done.org
3. log in
4. reload the page--you're logged out

Against dev, I'm seeing better behavior, as implemented by the #3905 fix:
1. open up safari, go to dev.123done.org
2. log in
3. reload the page--still logged in

However, we still see the problem where we cannot detect in a new tab that you've got an active session in another tab.

**Comment by callahad** [comment]
@6a68 Please verify that this is fixed in production.

**Comment by jaredhirsch** [comment]
@callahad yes, works for me on safari Version 7.0 (9537.71), last week's GM seed.

We should be fine when 10.9 is released to production.

**Comment by michaellenaghan** [comment]
I believe this is still a problem in both Safari 7 and Mobile Safari 7. In both browsers I can log into my app using Persona, but after reloading the page I'm no longer logged in. (Everything works as expected if I change Preferences from "Block third-party cookies" to "Never block cookies.")

I see people testing these issues against 123done.org. Indeed, 123done.org works--but I don't think the approach it takes matches what the docs suggest. Here's a snippet from 
[http://123done.org/js/123done.js](http://123done.org/js/123done.js):

``` javascript
  // now check with the server to get our current login state
  $.get('/api/auth_status', function(data) {
    loggedInEmail = JSON.parse(data).logged_in_email;

    function updateUI(email) {
        ...
    }

    function updateListArea(email) {
        ...
    }

    // register callbacks with the persona API to be invoked when
    // the user logs in or out.
    navigator.id.watch({
      // pass the currently logged in email address from the server's
      // session. This will cause onlogin/onlogout to not be invoked
      // when we're up to date.
      loggedInUser: loggedInEmail,
      ...
```

That code runs in `ready()`. Note that a) it immediately fires off a call to the server asking about the login state and b) it feeds the result into `navigator.id.watch()`. Or, to put it another way, it doesn't call `watch()` until it confirms whether or not the user is currently logged in. That seems reasonable, but I don't see that suggested in the [Quick Setup Guide](https://developer.mozilla.org/en-US/Persona/Quick_setup) or in the [Implementor's Guide](https://developer.mozilla.org/en-US/Persona/The_implementor_s_guide?redirectlocale=en-US&redirectslug=Persona%2FThe_implementor_s_guide). Hmmm, I do see it now on the [navigator.id API](https://developer.mozilla.org/en-US/Persona/The_navigator.id_API) page. Is this a doc problem rather than an implementation problem?
