### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by jrootham** [mozilla/persona#4117]
Verification is now returning error number 60 with message SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SS routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I assume this is fallout from the OpenSSH problem.  What do I need to do to fix it?

Also, I have inserted an exception in the PHP code, is that how you want this kind of error responded to?  IE should I migrate that code to the GitHub site?

**Comment by edwindotcom** [comment]
I can repro - ops is investigating

**Comment by gene1wood** [comment]
Yes, this is due to an unintentional certificate revocation related to Heartbleed. We're re-issuing a new cert and installing.

http://personastatus.org/#1397078370

**Comment by jaredhirsch** [comment]
@jrootham Thanks so much for opening this bug! :beers:

I'm not totally sure what you mean by:

"Also, I have inserted an exception in the PHP code, is that how you want this kind of error responded to? IE should I migrate that code to the GitHub site?"

**Comment by gene1wood** [comment]
Cert has been re-issued and the service is back up.

@jrootham feel free to re-open this if you're still experiencing problems. Apologies for the outage.

http://personastatus.org/#1397081880

**Comment by jrootham** [comment]
I'm using the PHP code posted on GitHub for server side processing.  I fixed it earlier, but it does not have any error handling.  I added an exception throw to my local copy.  Should I add that to the GitHub version, or how do you want to do error handling?

**Comment by jrgm** [comment]
works for me with updated certificate for gmail and yahoo addresses wiht ff28. Thanks @gene1wood

**Comment by jaredhirsch** [comment]
reopening as @jrootham is still seeing it. from #4119 (closed as a dupe):

"I'd like to reopen this. I am still experiencing the problem. Do I need to reset the certificate at my end?"

**Comment by gene1wood** [comment]
Ya, it looks like the old cert was indeed revoked

```
$ openssl ocsp -issuer DigiCert_SHA2_Secure_Server_CA.crt -cert multisan-identity-bridge.login.persona.org.crt.revoked -url http://ocsp.digicert.com -CAfile DigiCert_SHA2_Secure_Server_CA.crt 
WARNING: no nonce in response
Response Verify Failure
140330253465280:error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found:ocsp_vfy.c:85:
multisan-identity-bridge.login.persona.org.crt.revoked: revoked
    This Update: Apr  9 21:22:00 2014 GMT
    Next Update: Apr 16 21:37:00 2014 GMT
    Revocation Time: Apr  9 17:27:34 2014 GMT
```

and the new cert is good and not revoked

```
2014-04-09 15:54:12 ✔ gene@ruth ~/sandbox/certs$ openssl ocsp -issuer DigiCertSHA2ExtendedValidationServerCA.pem -cert multisan-identity-bridge.login.persona.org.crt -url http://ocsp.digicert.com -CAfile DigiCertSHA2ExtendedValidationServerCA.pem
WARNING: no nonce in response
Response Verify Failure
139699795261120:error:27069076:OCSP routines:OCSP_basic_verify:signer certificate not found:ocsp_vfy.c:85:
multisan-identity-bridge.login.persona.org.crt: good
    This Update: Apr  9 22:00:00 2014 GMT
    Next Update: Apr 16 22:15:00 2014 GMT
```

**Comment by jrootham** [comment]
So what do I need to do on my end?

**Comment by gene1wood** [comment]
@jrootham can you provide some steps to reproduce this so we can look at it?

**Comment by jrootham** [comment]
On my site if I log in with my Gmail account I get the error messages above.  Earlier signing on to Voost failed as well, now it works.  Do you want more details on the code?

**Comment by gene1wood** [comment]
Or a url to the site where you see the login failure, a screenshot, or a link to the code. Does signin to voost still fail? Can you share the URL and steps you're going through?

**Comment by jrootham** [comment]
URL http://devhats.tjddev.net/
Voost works now.
Server side code is from https://github.com/mozilla/browserid-cookbook
PHP
Is that enough?

**Comment by gene1wood** [comment]
@jrootham Was this working prior to 10:00AM PDT today, or are you testing out your new code for the first time today?

Can you try updating your certificate authority store as mentioned here and seeing if that fixes it? : http://stackoverflow.com/a/21114601/168874

**Comment by jrootham** [comment]
This has been working for months.
When I clicked on the certificate link I get an alert "This certificate is already installed as a certificate authority."

**Comment by gene1wood** [comment]
The likely cause of this is that we changed our certificate the other day. It's now issued by a new certificate authority. I suspect this new CA is not in your PHP installations list of allowed CAs.

@jrootham You'll need to not click on the link to the CA store, but instead download it to your server (with the PHP code) using something like wget.

**Comment by jrootham** [comment]
I followed the instructions above.  I am still getting the error.

**Comment by jaredhirsch** [comment]
@gene1wood bump. any other suggestions? ^^

**Comment by gene1wood** [comment]
@jrootham Can you share 
- the PHP code that you're using
- the on disk file location and name that you saved the certificate store to
- the file permissions on the ca store file that you downloaded
- the uid that your webserver runs as
- the output from the command `grep 'MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs' /path/to/cacert.pem'` where `/path/to/cacert.pem` is the full path to the downloaded cacert file
- the version of PHP you're running

**Comment by jrootham** [comment]
```
<?php

class Persona
{
    /**
     * Scheme, hostname and port
     */
    protected $audience;

    /**
     * Constructs a new Persona (optionally specifying the audience)
     */
    public function __construct($audience = NULL)
    {
        $this->audience = $audience ? $audience : $this->guessAudience();
    }

    /**
     * Verify the validity of the assertion received from the user
     *
     * @param string $assertion The assertion as received from the login dialog
     * @return object The response from the Persona online verifier
     */
    public function verifyAssertion($assertion)
    {
        $postdata = 'assertion=' . urlencode($assertion) . '&audience=' . urlencode($this->audience);

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://verifier.login.persona.org/verify");
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        $response = curl_exec($ch);

        $errno = curl_errno($ch);

        if ($errno != 0)
        {
            $error = curl_error($ch);
            throw new Exception("Persona error: curl error message: $error", $errno);
        }

        curl_close($ch);

        return json_decode($response);
    }

    /**
     * Guesses the audience from the web server configuration
     */
    protected function guessAudience()
    {
        $audience = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https://' : 'http://';
        $audience .= $_SERVER['SERVER_NAME'] . ':'.$_SERVER['SERVER_PORT'];
        return $audience;
    }
}
```

```
[root@tjddev etc]# ls -ld /etc/pki/tls
drwxr-xr-x 5 root root 4096 Apr 11 13:25 /etc/pki/tls
[root@tjddev etc]# ls -l /etc/pki/tls/cacert.pem
-rw-r--r-- 1 root root 244954 Apr 11 13:25 /etc/pki/tls/cacert.pem

[root@tjddev etc]# ps -le | grep httpd
5 S     0   699     1  0  80   0 - 10962 poll_s ?        00:07:46 httpd
5 S    48 19539   699  0  80   0 - 11345 semtim ?        00:00:00 httpd
5 S    48 19541   699  0  80   0 - 11402 semtim ?        00:00:00 httpd
5 S    48 19542   699  0  80   0 - 10962 ep_pol ?        00:00:00 httpd
5 S    48 19543   699  0  80   0 - 10962 semtim ?        00:00:00 httpd
```

I think this means root or user 48

```
[root@tjddev etc]# grep 'MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs' /etc/pki/tls/cacert.pem
MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBsMQswCQYDVQQG
```

PHP Version 5.2.10 from phpinfo()

**Comment by gene1wood** [comment]
Cool, thank you for the details. 

And can you either share your `php.ini` file (so I can see the `curl.cainfo` setting) or even better just add in the setting into the php code in the block of `setopt`s by adding this line

```
        curl_setopt($ch, CURLOPT_CAINFO, '/etc/pki/tls/cacert.pem');
```

and see if that helps.

If that doesn't fix it, I'd like to see if the problem relates to the persona php code or specifically between php and the verifiers cert. Can you run this code and paste the result back here?

```
<?php
        error_reporting(E_ALL);
        ini_set('display_errors', '1');
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://verifier.login.persona.org/verify");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_CAINFO, '/etc/pki/tls/cacert.pem');
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        $response = curl_exec($ch);
        print($response);
        print(curl_error($ch));
?>
```

**Comment by jrootham** [comment]
I added the code, it now works.  Apologies for being dense and fumble
fingered (I suspect that contributed to the issues).

**Comment by gene1wood** [comment]
Cool, glad I could help!
